application:
  name: MyRESTApplication
  version: 1.0.0

server:
  port: 8042

# Папка для загрузки файлов

logging:
  level:
    root: INFO  # Уровень логирования
    ru.netology.cloudservice: DEBUG  # Уровень логирования для вашего приложения

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Users
    username: postgres
    password: Qazxcds123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect



